### ISSUE TITLE
[Headsup] deprecation of manifest v2, enforcement of manifest v3 and separately the deprecation of websql

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1351]
When chromium switch off support for manifest v2 (Mv2) in June 2023 and enforce manifest v3 (Mv3) then DuckieTV will need significant updates if it is to continue to run in any of the chromium browsers.
Support for Mv3 began on Chromuim 88, and the Web Store stopped allowing new extensions with Mv2, but that does not impact Dtv since we lost access to the Web Store years ago when they changes their security policy which Dtv cannot comply with due to the nature of its purpose. 

(1) In theory the standalone build could continue to run as is, we would just stop upgrading NWJS and remain on the last chromium version that supports Mv2.
This is likely the option I will take, as I am not prepared to invest time to research, convert/replace/rewrite code.

A taste of what will become necessary:
To migrate to Mv3 will require some significant changes.
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/

Additionally, background scripts become service workers, which will need to change in a whole bunch of ways, as  timers need to move to alarms, among other requirements.
https://developer.chrome.com/docs/extensions/mv2/background_pages/

Also in the pipeline: Developers should expect that WebSQL itself will be deprecated and removed when usage is low enough. Chromium 101 already [Remove WebSQL in Third-Party Contexts](https://chromestatus.com/feature/5684870116278272) but this does not appear to impact Dtv.

I definitely will not be converting/migrating the websql code to Indexed Database ahead of websql being switched off, 
and will action option (1).

Unless, of course, some bright volunteer takes over and starts bringing Dtv up to date.

**Comment by IAmHugh001** [comment]
Think since no one seems to b e willing to bring DTV up to date it's time to finally die, cause if it's not a security risk now it will be. I'm heading over to Tweak4All and ask Han's if he's interested or knows someone interested in breathing life into DTV. I for one would love to see it survive as a proper alternative to Sonarr. Without a lot of the CRAP the Sonarr devs think are important.

**Comment by garfield69** [comment]
Its happened. Chromium 119 has removed Web SQL 
https://developer.chrome.com/blog/deprecating-web-sql/

So Dtv will not longer work on chrome browser.

That leaves only Dtv Standalone where we can lock in the last chromium to 118 for as long as that keeps running.

**Comment by Js41637** [comment]
You can get WebSQL back by enabling a chrome flag, i am unsure when and if they will be removing it though.
chrome://flags/#web-sql-access

**Comment by garfield69** [comment]
With Chromium 124 the WEB SQL support has been removed.

**Comment by Js41637** [comment]
I don't know how but I somehow managed to get manifest V3 working and replaced using WebSQL with SQLite though i have not really tested it much yet but it loads and i can add a show.
https://github.com/SchizoDuckie/DuckieTV/compare/angular...feat/manifest-v3-insanity

WebSQL is basically identical to Sqlite so there really isn't any changes needed except for a couple edge cases. The only real problem is using sqlite as it requires web assembly and Chrome has made it really painful to use without having to jump through a heap of hoops 😒

**Comment by daibjork** [comment]
So, any plans on switching to SQLite instead of WebSQL för the browser extension? Been using DuckieTV for several years and I'm now on the "last" Chrome version where you still can activate WebSQL. Tried the standalone version, but it just hangs and won't start most of the time (Macbook Pro, M1). Tried Sonarr briefly but I didn't like it as much as I do with DuckieTV which, as I said, has been a steady companion for years... so, any thought on migrating to SQLite?

**Comment by Js41637** [comment]
Well there is the branch which you could try I guess. It seems to work but I suspect the performance is not going to be as good as there is more hoops to jump through when using sqlite compared to websql. It would also require importing a backup as there is no way to migrate existing data.

I was looking into if we can build a proper ARM build of the standalone version to see if it would work better for macs but the build tool is basically impossible to test and we have little control over it....

**Comment by garfield69** [comment]
@dewerl 
Have you tried https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-run-a-DuckieTV-Standalone-for-osX-ARM64 ?

If that does not work then you there is a SQLite WIP available as source. Fork this repo and switch to the manifest-v3-insanity branch. You can then try it with a Browser Extension in development mode, see https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-DuckieTV-Chrome-Browser-Extension-SOURCE
Only the TAB mode manifest is provided, and there is no migration available other than via a Dtv backup import.

**Comment by garfield69** [comment]
@Js41637  Is the mac ARM build going to be exactly the same duckietv-builder code as the mac x64, other than using the ARM NWJS binaries ?
Because if it is identical in every other way, then I can readily duplicate that builder code and create a ARM package for someone to test with.
However, if there are additional package changes needed, such as a different mac archive method, then that is where I will become unstuck.

**Comment by Js41637** [comment]
I think it is possible to add arm support to the build script but I cannot test it, it depends on programs and tools that I don't have and I cannot find. I managed to test the building and making the binary but the package binary part I cannot run. It's possible it just works but I am not sure. I pushed it to a branch https://github.com/DuckieTV/duckietv-builder/commit/9880d5d903b743d56ae63e41297a738b45b64341

As for the sqlite thing. Another thing is it uses some special chrome storage thing. I don't really understand how it works or how persistent the storage is. Another downside is it's impossible to access the database file externally. Chrome stores it in some special way that is only accessable to Chrome.

**Comment by garfield69** [comment]
I will see if I can use that duckietv-builder branch to create a ARM nightly and I'll post a link to the package if I can get my builder to generate it.

**Comment by garfield69** [comment]
@Js41637  find the arm package at this temporary location https://github.com/SchizoDuckie/DuckieTV/releases/tag/1.1.6
however, the osx.js is not set up correctly for multiple arch, as after packaging the x64, if fails to begin the arm64, with
```
Packaging: DuckieTV-202405101613-OSX-arm64.pkg
/home/garfield69/duckietv-builder/node_modules/shelljs/src/common.js:401
      if (config.fatal) throw e;
                        ^
Error: cp: no such file or directory: /home/garfield69/duckietv-builder/platforms/osx/build/*
    at Object.error (/home/garfield69/duckietv-builder/node_modules/shelljs/src/common.js:110:27)
    at /home/garfield69/duckietv-builder/node_modules/shelljs/src/cp.js:246:14
    at Array.forEach (<anonymous>)
    at _cp (/home/garfield69/duckietv-builder/node_modules/shelljs/src/cp.js:243:11)
    at /home/garfield69/duckietv-builder/node_modules/shelljs/src/common.js:384:25
    at /home/garfield69/duckietv-builder/platforms/osx.js:95:17
    at Array.map (<anonymous>)
    at Object.packageBinary (/home/garfield69/duckietv-builder/platforms/osx.js:82:27)
    at /home/garfield69/duckietv-builder/duckietv-builder-package-binaries.js:37:15
    at Array.map (<anonymous>)
```
I was able to circumvent by reordering the architectures from x64,arm64 to arm64,x64, but that meant that the x64 packaging fails instead.

**Comment by Js41637** [comment]
The ARM version seems to work great. I haven't noticed any freezing that happened with the x64 version yet.

I have no idea what that error means though. The code that line is on seems unchanged from the original, that folder should exist it's not related to the build? And makes no sense it would work for one and not the next unless it's getting deleted somehow?

**Comment by garfield69** [comment]
I'm guessing that you took the packagebinary block and simply wrapped it in an arch map, but the original clearly made some makedir/deletedir steps which now they are in a loop cause the second iteration to fail.
I'll try to turn on debugging so I can get a more detailed dump of the activity to point the culprit statement.

**Comment by garfield69** [comment]
@dewerl  Please try out the arm64 package at https://github.com/DuckieTV/Nightlies/releases/latest and let us know how it goes.
[edit] updated the link

**Comment by Js41637** [comment]
> I'm guessing that you took the packagebinary block and simply wrapped it in an arch map, but the original clearly made some makedir/deletedir steps which now they are in a loop cause the second iteration to fail. I'll try to turn on debugging so I can get a more detailed dump of the activity to point the culprit statement.

Additional changes were made to make it support the arch, the fact it works once for either platform means it works.

```
rm('-rf', WORK_DIR); // init work dir
mkdir('-p', WORK_DIR);
mkdir('-p', APP_BUILD_DIR);

cp('-r', RESOURCE_DIR + '/*', WORK_DIR); // initialize base directory structure
cp('-r', BINARY_OUTPUT_DIR + '/*', APP_BUILD_DIR); // copy source files to installer base
mkdir('-p', BINARY_OUTPUT_DIR);
cd(APP_BUILD_DIR);
```

The `RESOURCE_DIR` (`home/garfield69/duckietv-builder/platforms/osx/build/`) is not part of the build script, its a static folder that exists in the repo and is commited. According to the error, the part that fails is this 
```
cp('-r', RESOURCE_DIR + '/*', WORK_DIR); // initialize base directory structure
```

This just seems to copy files from the resource dir to the work dir. I don't see how the resource dir can't exist because no where in the code or the original code is that folder removed, it's a commited folder in the repo so it's not edited by the build process. And `WORK_DIR` also has to exist because it's removed at the start of that script and then made again.

**Comment by garfield69** [comment]
I put echo with 'debug' in front of all the statements 
```
Packaging binaries
Running packager processor for osx
Packaging: DuckieTV-202405101914-OSX-x64.pkg
debug rm -rf workdir
debug mkdir -p workdir
debug mkdir -p appbuilddir
debug cp -r resourcedir
debug cp-r binaryoutputdir
debug mkdir -p binaryoutputdir
debug cd appbuilddir
Counting files: 
621
Determining full install size in KB
339592
debug cat workdir/flat/dist
debug cat workdir /flat/base
debug exec chmod
675791 blocks
debug exec mkbon
debug pushd
/home/garfield69/duckietv-builder/TMP/osx-installer/flat /home/garfield69/duckietv-builder/TMP/osx-installer/root
debug xar
Done building for OSX, see /home/garfield69/duckietv-builder/binaries/DuckieTV-202405101914-OSX-x64.pkg
Packaging: DuckieTV-202405101914-OSX-arm64.pkg
debug rm -rf workdir
debug mkdir -p workdir
debug mkdir -p appbuilddir
debug cp -r resourcedir
/home/garfield69/duckietv-builder/node_modules/shelljs/src/common.js:401
      if (config.fatal) throw e;
                        ^
Error: cp: no such file or directory: /home/garfield69/duckietv-builder/platforms/osx/build/*
    at Object.error (/home/garfield69/duckietv-builder/node_modules/shelljs/src/common.js:110:27)
    at /home/garfield69/duckietv-builder/node_modules/shelljs/src/cp.js:246:14
    at Array.forEach (<anonymous>)
    at _cp (/home/garfield69/duckietv-builder/node_modules/shelljs/src/cp.js:243:11)
    at /home/garfield69/duckietv-builder/node_modules/shelljs/src/common.js:384:25
    at /home/garfield69/duckietv-builder/platforms/osx.js:107:17
    at Array.map (<anonymous>)
    at Object.packageBinary (/home/garfield69/duckietv-builder/platforms/osx.js:90:27)
    at /home/garfield69/duckietv-builder/duckietv-builder-package-binaries.js:37:15
    at Array.map (<anonymous>)
```
it fails in the second iteration on the copy resourcedir/* to workdir at line 95

**Comment by garfield69** [comment]
oh, you worked that out already ;-)

**Comment by garfield69** [comment]
are the changedirectories impacting the copy, do we need to reset back to someplace at the start of the loop?

**Comment by garfield69** [comment]
fixed it. added cd(__dirname); at the start of the loop

**Comment by daibjork** [comment]
Hi, thanks for the effort guys! Tested both the insanity-branch browser extension and the arm64 package. 

The browser extension works pretty good! It's a bit slow importing a backup (~175 shows). I read your heads up about that but other than that I think it performs rather well (the things I've tried, automatic downloading, searching etc. - no issue here). One drawback for me it that's it only the new tab (for now?) as I've been using the browser action extension for years. I have other things set up for my new tab that I need and constantly working with in my work so a browser action extension would be much preferred of course.

The arm64 package works much much better than the Intel package on my Macbook Pro M1 Pro. Loads great, no hangs, importing a backup from browser action extension - no problem, downloading, searching all ok. One thing I've noticed is that it seems that it's not saving the window position or if the window is maximized. When quiting and starting it again the window position is back to default (centered and not maximized etc.).

I very much appreciate you fixing this as DuckieTV is very much one extension I just can't live without 😊.

Thanks again!

**Comment by daibjork** [comment]
@Js41637 Any plans or thoughts on doing the same change you did with WebSQL -> SQLite for the browser action extension?

**Comment by daibjork** [comment]
> @Js41637 Any plans or thoughts on doing the same change you did with WebSQL -> SQLite for the browser action extension?

Any plans on fixing the browser action extension? Thanks.

**Comment by daibjork** [comment]
Hi, saw that there was a new version released. No updates for the browser action extension and the WebSQL "issue" right (couldn't see anything about it in the release notes anyway)? Don't want to upgrade my browser and find out that the browser action extension stops working. Thanks.

**Comment by garfield69** [comment]
only changed the mirror resolver for the search engine TPB

**Comment by daibjork** [comment]
Thanks for the info! Any plans on implementing the WebSQL -> SQLite "fix" for the browser action extension? Seems to work when I tested it anyway?

**Comment by garfield69** [comment]
> Any plans on implementing the WebSQL -> SQLite "fix" for the browser action extension? 

I'm the wrong person to ask.
I took a look. the code that  enables the browser button to launch dtv action mode is what needs to be updated, everything else is the same code as for the dtv tab mode.
However I cannot figure out how to convert the background launch script to service worker script.  Not my cup of tea.

**Comment by daibjork** [comment]
Thanks, appreciate it! I understand. I'm just curious if it's something you consider to fix eventually? 
So, it doesn't sound that it's that much work then to "switch" to the SQLite route? Is it something that @Js41637 is more familiar with and can sort out perhaps?

**Comment by garfield69** [comment]
It will not go mainline until NWJS supports v3 manifests so that standalone builds work.
At the moment NWJS works on v2 manifests and appears to patch chromium 125 with WEBSQL support so there is no urgency to switch to sqlite+v3 manifest.
I will not try to support two different streams of Dtv, one for standalone and the other for browsers. I don't have time to support both flavours and I prefer to give standalone priority.

**Comment by daibjork** [comment]
Ok, got it. Thanks for your answer. Then I know a bit more on your thoughts going forward ✌🏻
