### ISSUE TITLE
Hide Series from Calendar no longer works

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#846]
Moved from #843 as I don't think this is related.     
Issue: From the Series details side panel, using the *Hide Series on Calendar!* does not work any longer.
I will investigate.

**Comment by garfield69** [comment]
OK.     
This was broken by commit 8994d3f8e9efd0f16d458e8bd9732fa65066362a as part of #818.    
Js41637 removed the filterEvents support from the DataPicker.js directive, presumably believing it was used only by templates/todopicker.html which he was reworking.    
```javascript
scope.filterEvents = function(event) {
    if (!event.serie) return false;
    if (event.serie.displaycalendar == 0) return false;
    else return true;
};
```
Unfortunately filterEvents is also used by templates\datepicker.html, hence the issue.
I will re-instate the filter in the appropriate place.

**Comment by SchizoDuckie** [comment]
Should we perhaps define this as an angularjs global $filter extension
instead of a $scope function to prevent this from happening again?

**Comment by garfield69** [comment]
>Should we perhaps define this as an angularjs global $filter extension instead of a $scope function to prevent this from happening again?    

a global $filter extension... I'm not sure how to do this. Can you point me to an example?

**Comment by SchizoDuckie** [comment]
```
// To declare a filter we pass in two parameters to app.filter

// The first parameter is the name of the filter 
// second is a function that will return another function that does the actual work of the filter

app.filter('myFilter', function() {

  // In the return function, we must pass in a single parameter which will be the data we will work on.
  // We have the ability to support multiple other parameters that can be passed into the filter optionally
  return function(input, optional1, optional2) {

    var output;

    // Do filter work here

    return output;

  }

});```

**Comment by garfield69** [comment]
yeah, so that is what I thought you were talking about. so I set up this in app.js
```javascript
/**
 * Filter for calendar events as used by templates/datepicker.html for instance.
 */
.filter('filterEvents', ["event",
    function(event) {
        if (!event.serie) return false;
        if (event.serie.displaycalendar == 0) return false;
        else return true;
    }
])
```
and dropped the scope.filterEvents from the datePicker directive.
but what do I change in the datepicket.html to use the global filter? 
```
            <calendar-event serie="event.serie" episode="event.episode" ng-if="hasEvent(day)" ng-repeat="event in getEvents(day)|filter:filterEvents|orderBy:['episode.getAirTime()','serie.name','episode.getFormattedEpisode()']"></calendar-event>
```

**Comment by SchizoDuckie** [comment]
As far as I know, that is it :)  your filter should now work everywhere

**Comment by garfield69** [comment]
I'm getting
```
Error: [$injector:unpr] Unknown provider: eventProvider <- event <- filterEventsFilter
http://errors.angularjs.org/1.5.10/$injector/unpr?p0=eventProvider%20%3C-%20event%20%3C-NaNilterEventsFilter
    at chrome-extension://dnpkofmmnjbhijiebfeaibhbbgijjnch/js/vendor/angular.js:68:12
    at chrome-extension://dnpkofmmnjbhijiebfeaibhbbgijjnch/js/vendor/angular.js:4559:19
    at Object.getService [as get] (chrome-extension://dnpkofmmnjbhijiebfeaibhbbgijjnch/js/vendor/angular.js:4712:32)
    at chrome-extension://dnpkofmmnjbhijiebfeaibhbbgijjnch/js/vendor/angular.js:4564:45
    at getService (chrome-extension://dnpkofmmnjbhijiebfeaibhbbgijjnch/js/vendor/angular.js:4712:32)
    at injectionArgs (chrome-extension://dnpkofmmnjbhijiebfeaibhbbgijjnch/js/vendor/angular.js:4737:58)
    at Object.invoke (chrome-extension://dnpkofmmnjbhijiebfeaibhbbgijjnch/js/vendor/angular.js:4759:18)
    at Object.enforcedReturnValue [as $get] (chrome-extension://dnpkofmmnjbhijiebfeaibhbbgijjnch/js/vendor/angular.js:4605:37)
    at Object.invoke (chrome-extension://dnpkofmmnjbhijiebfeaibhbbgijjnch/js/vendor/angular.js:4767:19)
    at chrome-extension://dnpkofmmnjbhijiebfeaibhbbgijjnch/js/vendor/angular.js:4565:37
(anonymous) @ angular.js:14195
2017-02-17 06:42:29.589 
```

**Comment by garfield69** [comment]
I'll dig deeper after I've had some coffee. I'm not awake yet. Ignore the previous post about the error.

**Comment by garfield69** [comment]
sorted. (I mean filtered!) :-)

**Comment by SchizoDuckie** [comment]
Excellent!
